package com.zy1401Team2.OSService.bean;

import java.io.Serializable;

public class MenuType implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu_type.menu_type_id
     *
     * @mbggenerated
     */
    private Integer menuTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu_type.menu_id
     *
     * @mbggenerated
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu_type.type_id
     *
     * @mbggenerated
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_menu_type
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu_type.menu_type_id
     *
     * @return the value of tb_menu_type.menu_type_id
     *
     * @mbggenerated
     */
    public Integer getMenuTypeId() {
        return menuTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu_type.menu_type_id
     *
     * @param menuTypeId the value for tb_menu_type.menu_type_id
     *
     * @mbggenerated
     */
    public void setMenuTypeId(Integer menuTypeId) {
        this.menuTypeId = menuTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu_type.menu_id
     *
     * @return the value of tb_menu_type.menu_id
     *
     * @mbggenerated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu_type.menu_id
     *
     * @param menuId the value for tb_menu_type.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu_type.type_id
     *
     * @return the value of tb_menu_type.type_id
     *
     * @mbggenerated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu_type.type_id
     *
     * @param typeId the value for tb_menu_type.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_type
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MenuType other = (MenuType) that;
        return (this.getMenuTypeId() == null ? other.getMenuTypeId() == null : this.getMenuTypeId().equals(other.getMenuTypeId()))
            && (this.getMenuId() == null ? other.getMenuId() == null : this.getMenuId().equals(other.getMenuId()))
            && (this.getTypeId() == null ? other.getTypeId() == null : this.getTypeId().equals(other.getTypeId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_type
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMenuTypeId() == null) ? 0 : getMenuTypeId().hashCode());
        result = prime * result + ((getMenuId() == null) ? 0 : getMenuId().hashCode());
        result = prime * result + ((getTypeId() == null) ? 0 : getTypeId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_type
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuTypeId=").append(menuTypeId);
        sb.append(", menuId=").append(menuId);
        sb.append(", typeId=").append(typeId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}