package com.zy1401Team2.OSService.bean;

import java.io.Serializable;

public class Menu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menu_id
     *
     * @mbggenerated
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menu_name
     *
     * @mbggenerated
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menu_introduce
     *
     * @mbggenerated
     */
    private String menuIntroduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menu_address
     *
     * @mbggenerated
     */
    private String menuAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menu_price
     *
     * @mbggenerated
     */
    private Double menuPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menu_cutprice
     *
     * @mbggenerated
     */
    private Double menuCutprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menu_discount
     *
     * @mbggenerated
     */
    private Double menuDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menu_is_discount
     *
     * @mbggenerated
     */
    private Boolean menuIsDiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menu_is_decommend
     *
     * @mbggenerated
     */
    private Boolean menuIsDecommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menu_is_order
     *
     * @mbggenerated
     */
    private Boolean menuIsOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menu_pic_url
     *
     * @mbggenerated
     */
    private String menuPicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menu_order_count
     *
     * @mbggenerated
     */
    private Integer menuOrderCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menu_create_date
     *
     * @mbggenerated
     */
    private String menuCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.menu_status
     *
     * @mbggenerated
     */
    private Boolean menuStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_menu.sort_id
     *
     * @mbggenerated
     */
    private Integer sortId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_menu
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menu_id
     *
     * @return the value of tb_menu.menu_id
     *
     * @mbggenerated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menu_id
     *
     * @param menuId the value for tb_menu.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menu_name
     *
     * @return the value of tb_menu.menu_name
     *
     * @mbggenerated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menu_name
     *
     * @param menuName the value for tb_menu.menu_name
     *
     * @mbggenerated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menu_introduce
     *
     * @return the value of tb_menu.menu_introduce
     *
     * @mbggenerated
     */
    public String getMenuIntroduce() {
        return menuIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menu_introduce
     *
     * @param menuIntroduce the value for tb_menu.menu_introduce
     *
     * @mbggenerated
     */
    public void setMenuIntroduce(String menuIntroduce) {
        this.menuIntroduce = menuIntroduce == null ? null : menuIntroduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menu_address
     *
     * @return the value of tb_menu.menu_address
     *
     * @mbggenerated
     */
    public String getMenuAddress() {
        return menuAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menu_address
     *
     * @param menuAddress the value for tb_menu.menu_address
     *
     * @mbggenerated
     */
    public void setMenuAddress(String menuAddress) {
        this.menuAddress = menuAddress == null ? null : menuAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menu_price
     *
     * @return the value of tb_menu.menu_price
     *
     * @mbggenerated
     */
    public Double getMenuPrice() {
        return menuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menu_price
     *
     * @param menuPrice the value for tb_menu.menu_price
     *
     * @mbggenerated
     */
    public void setMenuPrice(Double menuPrice) {
        this.menuPrice = menuPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menu_cutprice
     *
     * @return the value of tb_menu.menu_cutprice
     *
     * @mbggenerated
     */
    public Double getMenuCutprice() {
        return menuCutprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menu_cutprice
     *
     * @param menuCutprice the value for tb_menu.menu_cutprice
     *
     * @mbggenerated
     */
    public void setMenuCutprice(Double menuCutprice) {
        this.menuCutprice = menuCutprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menu_discount
     *
     * @return the value of tb_menu.menu_discount
     *
     * @mbggenerated
     */
    public Double getMenuDiscount() {
        return menuDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menu_discount
     *
     * @param menuDiscount the value for tb_menu.menu_discount
     *
     * @mbggenerated
     */
    public void setMenuDiscount(Double menuDiscount) {
        this.menuDiscount = menuDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menu_is_discount
     *
     * @return the value of tb_menu.menu_is_discount
     *
     * @mbggenerated
     */
    public Boolean getMenuIsDiscount() {
        return menuIsDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menu_is_discount
     *
     * @param menuIsDiscount the value for tb_menu.menu_is_discount
     *
     * @mbggenerated
     */
    public void setMenuIsDiscount(Boolean menuIsDiscount) {
        this.menuIsDiscount = menuIsDiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menu_is_decommend
     *
     * @return the value of tb_menu.menu_is_decommend
     *
     * @mbggenerated
     */
    public Boolean getMenuIsDecommend() {
        return menuIsDecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menu_is_decommend
     *
     * @param menuIsDecommend the value for tb_menu.menu_is_decommend
     *
     * @mbggenerated
     */
    public void setMenuIsDecommend(Boolean menuIsDecommend) {
        this.menuIsDecommend = menuIsDecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menu_is_order
     *
     * @return the value of tb_menu.menu_is_order
     *
     * @mbggenerated
     */
    public Boolean getMenuIsOrder() {
        return menuIsOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menu_is_order
     *
     * @param menuIsOrder the value for tb_menu.menu_is_order
     *
     * @mbggenerated
     */
    public void setMenuIsOrder(Boolean menuIsOrder) {
        this.menuIsOrder = menuIsOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menu_pic_url
     *
     * @return the value of tb_menu.menu_pic_url
     *
     * @mbggenerated
     */
    public String getMenuPicUrl() {
        return menuPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menu_pic_url
     *
     * @param menuPicUrl the value for tb_menu.menu_pic_url
     *
     * @mbggenerated
     */
    public void setMenuPicUrl(String menuPicUrl) {
        this.menuPicUrl = menuPicUrl == null ? null : menuPicUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menu_order_count
     *
     * @return the value of tb_menu.menu_order_count
     *
     * @mbggenerated
     */
    public Integer getMenuOrderCount() {
        return menuOrderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menu_order_count
     *
     * @param menuOrderCount the value for tb_menu.menu_order_count
     *
     * @mbggenerated
     */
    public void setMenuOrderCount(Integer menuOrderCount) {
        this.menuOrderCount = menuOrderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menu_create_date
     *
     * @return the value of tb_menu.menu_create_date
     *
     * @mbggenerated
     */
    public String getMenuCreateDate() {
        return menuCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menu_create_date
     *
     * @param menuCreateDate the value for tb_menu.menu_create_date
     *
     * @mbggenerated
     */
    public void setMenuCreateDate(String menuCreateDate) {
        this.menuCreateDate = menuCreateDate == null ? null : menuCreateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.menu_status
     *
     * @return the value of tb_menu.menu_status
     *
     * @mbggenerated
     */
    public Boolean getMenuStatus() {
        return menuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.menu_status
     *
     * @param menuStatus the value for tb_menu.menu_status
     *
     * @mbggenerated
     */
    public void setMenuStatus(Boolean menuStatus) {
        this.menuStatus = menuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_menu.sort_id
     *
     * @return the value of tb_menu.sort_id
     *
     * @mbggenerated
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_menu.sort_id
     *
     * @param sortId the value for tb_menu.sort_id
     *
     * @mbggenerated
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Menu other = (Menu) that;
        return (this.getMenuId() == null ? other.getMenuId() == null : this.getMenuId().equals(other.getMenuId()))
            && (this.getMenuName() == null ? other.getMenuName() == null : this.getMenuName().equals(other.getMenuName()))
            && (this.getMenuIntroduce() == null ? other.getMenuIntroduce() == null : this.getMenuIntroduce().equals(other.getMenuIntroduce()))
            && (this.getMenuAddress() == null ? other.getMenuAddress() == null : this.getMenuAddress().equals(other.getMenuAddress()))
            && (this.getMenuPrice() == null ? other.getMenuPrice() == null : this.getMenuPrice().equals(other.getMenuPrice()))
            && (this.getMenuCutprice() == null ? other.getMenuCutprice() == null : this.getMenuCutprice().equals(other.getMenuCutprice()))
            && (this.getMenuDiscount() == null ? other.getMenuDiscount() == null : this.getMenuDiscount().equals(other.getMenuDiscount()))
            && (this.getMenuIsDiscount() == null ? other.getMenuIsDiscount() == null : this.getMenuIsDiscount().equals(other.getMenuIsDiscount()))
            && (this.getMenuIsDecommend() == null ? other.getMenuIsDecommend() == null : this.getMenuIsDecommend().equals(other.getMenuIsDecommend()))
            && (this.getMenuIsOrder() == null ? other.getMenuIsOrder() == null : this.getMenuIsOrder().equals(other.getMenuIsOrder()))
            && (this.getMenuPicUrl() == null ? other.getMenuPicUrl() == null : this.getMenuPicUrl().equals(other.getMenuPicUrl()))
            && (this.getMenuOrderCount() == null ? other.getMenuOrderCount() == null : this.getMenuOrderCount().equals(other.getMenuOrderCount()))
            && (this.getMenuCreateDate() == null ? other.getMenuCreateDate() == null : this.getMenuCreateDate().equals(other.getMenuCreateDate()))
            && (this.getMenuStatus() == null ? other.getMenuStatus() == null : this.getMenuStatus().equals(other.getMenuStatus()))
            && (this.getSortId() == null ? other.getSortId() == null : this.getSortId().equals(other.getSortId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMenuId() == null) ? 0 : getMenuId().hashCode());
        result = prime * result + ((getMenuName() == null) ? 0 : getMenuName().hashCode());
        result = prime * result + ((getMenuIntroduce() == null) ? 0 : getMenuIntroduce().hashCode());
        result = prime * result + ((getMenuAddress() == null) ? 0 : getMenuAddress().hashCode());
        result = prime * result + ((getMenuPrice() == null) ? 0 : getMenuPrice().hashCode());
        result = prime * result + ((getMenuCutprice() == null) ? 0 : getMenuCutprice().hashCode());
        result = prime * result + ((getMenuDiscount() == null) ? 0 : getMenuDiscount().hashCode());
        result = prime * result + ((getMenuIsDiscount() == null) ? 0 : getMenuIsDiscount().hashCode());
        result = prime * result + ((getMenuIsDecommend() == null) ? 0 : getMenuIsDecommend().hashCode());
        result = prime * result + ((getMenuIsOrder() == null) ? 0 : getMenuIsOrder().hashCode());
        result = prime * result + ((getMenuPicUrl() == null) ? 0 : getMenuPicUrl().hashCode());
        result = prime * result + ((getMenuOrderCount() == null) ? 0 : getMenuOrderCount().hashCode());
        result = prime * result + ((getMenuCreateDate() == null) ? 0 : getMenuCreateDate().hashCode());
        result = prime * result + ((getMenuStatus() == null) ? 0 : getMenuStatus().hashCode());
        result = prime * result + ((getSortId() == null) ? 0 : getSortId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", menuId=").append(menuId);
        sb.append(", menuName=").append(menuName);
        sb.append(", menuIntroduce=").append(menuIntroduce);
        sb.append(", menuAddress=").append(menuAddress);
        sb.append(", menuPrice=").append(menuPrice);
        sb.append(", menuCutprice=").append(menuCutprice);
        sb.append(", menuDiscount=").append(menuDiscount);
        sb.append(", menuIsDiscount=").append(menuIsDiscount);
        sb.append(", menuIsDecommend=").append(menuIsDecommend);
        sb.append(", menuIsOrder=").append(menuIsOrder);
        sb.append(", menuPicUrl=").append(menuPicUrl);
        sb.append(", menuOrderCount=").append(menuOrderCount);
        sb.append(", menuCreateDate=").append(menuCreateDate);
        sb.append(", menuStatus=").append(menuStatus);
        sb.append(", sortId=").append(sortId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}