package com.zy1401Team2.OSService.bean;

import java.io.Serializable;

public class Test implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.test_id
     *
     * @mbggenerated
     */
    private Integer testId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.test_name
     *
     * @mbggenerated
     */
    private String testName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test.test_message
     *
     * @mbggenerated
     */
    private String testMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_test
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.test_id
     *
     * @return the value of t_test.test_id
     *
     * @mbggenerated
     */
    public Integer getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.test_id
     *
     * @param testId the value for t_test.test_id
     *
     * @mbggenerated
     */
    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.test_name
     *
     * @return the value of t_test.test_name
     *
     * @mbggenerated
     */
    public String getTestName() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.test_name
     *
     * @param testName the value for t_test.test_name
     *
     * @mbggenerated
     */
    public void setTestName(String testName) {
        this.testName = testName == null ? null : testName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test.test_message
     *
     * @return the value of t_test.test_message
     *
     * @mbggenerated
     */
    public String getTestMessage() {
        return testMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test.test_message
     *
     * @param testMessage the value for t_test.test_message
     *
     * @mbggenerated
     */
    public void setTestMessage(String testMessage) {
        this.testMessage = testMessage == null ? null : testMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Test other = (Test) that;
        return (this.getTestId() == null ? other.getTestId() == null : this.getTestId().equals(other.getTestId()))
            && (this.getTestName() == null ? other.getTestName() == null : this.getTestName().equals(other.getTestName()))
            && (this.getTestMessage() == null ? other.getTestMessage() == null : this.getTestMessage().equals(other.getTestMessage()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTestId() == null) ? 0 : getTestId().hashCode());
        result = prime * result + ((getTestName() == null) ? 0 : getTestName().hashCode());
        result = prime * result + ((getTestMessage() == null) ? 0 : getTestMessage().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", testId=").append(testId);
        sb.append(", testName=").append(testName);
        sb.append(", testMessage=").append(testMessage);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}