package com.zy1401Team2.OSService.dao;

import com.zy1401Team2.OSService.bean.MenuType;

public interface MenuTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer menuTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_type
     *
     * @mbggenerated
     */
    int insert(MenuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_type
     *
     * @mbggenerated
     */
    int insertSelective(MenuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_type
     *
     * @mbggenerated
     */
    MenuType selectByPrimaryKey(Integer menuTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MenuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MenuType record);
    
}