package com.zy1401Team2.OSService.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.zy1401Team2.OSService.bean.Menu;

@Repository(value="menuDao")
public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu
     *
     * @mbggenerated
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu
     *
     * @mbggenerated
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu
     *
     * @mbggenerated
     */
    Menu selectByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Menu record);
    
    List<Menu> selectAllMenu();
    
    List<Menu> selectByType(int typeId);
    
    List<Menu> selectLikeName(String shortName);
}